### ISSUE TITLE
Doesn't build

### ISSUE THREAD

**Issue by Drup** [OCamlPro/ocp-ocamlres#3]
Opam and git version don't build, here is the output :
```
File "src/oCamlResFormats.ml", line 20, characters 0-23:
Error: Unbound module OCamlResSubFormats
Makefile:53: recipe for target 'src/oCamlResFormats.cmo' failed
make: *** [src/oCamlResFormats.cmo] Error 2
rm src/oCamlResScanners.cmo src/oCamlRes.cmi src/oCamlRes.cmo src/oCamlResSubFormats.cmo
```

Also, there is a makefile *and* a build.ocp, is that intended ? `make clean` doesn't clean up .cmt*.

**Comment by klakplok** [comment]
Ok I never managed to have the errors that people talked about, so I dumbed the Makefile down.
